version: '3.8'

networks:
  pepita-network:
    driver: bridge

volumes:
  dbdata:

services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    restart: unless-stopped
    tty: true
    volumes:
      - "./.docker/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pepita_task
    ports:
      - "5432:5432"
    networks:
      - pepita-network

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pepita-network

  backend:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: pepita_backend
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pepita-network
    depends_on:
      - postgres
      - webserver